#30 create cdn and serve s3 bucket from cdn

diff --git a/bin/set_tf_alias b/bin/set_tf_alias
--- a/bin/set_tf_alias
+++ b/bin/set_tf_alias
@@ -1,15 +1,17 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# Define the alias to be added
-ALIAS_NAME="tf"
-ALIAS_COMMAND="terraform"
+# Check if the alias already exists in the .bash_profile
+grep -q 'alias tf="terraform"' ~/.bash_profile
 
-# Check if the alias already exists in ~/.bash_profile
-if ! grep -q "alias $ALIAS_NAME=" ~/.bash_profile; then
-  echo "alias $ALIAS_NAME='$ALIAS_COMMAND'" >> ~/.bash_profile
-  source ~/.bash_profile
-  echo "The '$ALIAS_NAME' alias has been added to ~/.bash_profile. You can now use it as a shorthand for '$ALIAS_COMMAND'."
+# $? is a special variable in bash that holds the exit status of the last command executed
+if [ $? -ne 0 ]; then
+    # If the alias does not exist, append it
+    echo 'alias tf="terraform"' >> ~/.bash_profile
+    echo "Alias added successfully."
 else
-  echo "The '$ALIAS_NAME' alias already exists in ~/.bash_profile."
+    # Inform the user if the alias already exists
+    echo "Alias already exists in .bash_profile."
 fi
 
+# Optional: source the .bash_profile to make the alias available immediately
+source ~/.bash_profile
